name: Check Prometheus Alert rules

on:
  pull_request:
    paths:
    - 'helm/**'

jobs:
  on-pull-request:
    name: On Pull Request
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master

    - uses: alexellis/setup-arkade@v1

    - uses: alexellis/arkade-get@master
      with:
        helm: v3.10.1
        yq: v4.28.1

    - run: |
        helm template . -s templates/prometheusrule.yaml | yq .spec > ${GITHUB_WORKSPACE}/promtool-rules.yaml
        ls -ltr ${GITHUB_WORKSPACE}
      working-directory: helm

    - name: Check Prometheus alert rules
      uses: peimanja/promtool-github-actions@master
      with:
        promtool_actions_subcommand: 'rules'
        promtool_actions_files: "promtool-rules.yaml"
        promtool_actions_version: '2.14.0'
        promtool_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
